### PR TITLE
Bump babel version

### PR DESCRIPTION
**Pull request by markthethomas**
Just some housekeeping; bumping version of babel to the most recent one. I think people are generally more likely to use a module if they see up-to-date deps :) thanks for working on this!

### CODE REVIEW

**Comment by dozoisch** [comment]
That's def true man! Thanks, I'll try to tag the version tonight! I've been so busy lately!

**Comment by markthethomas** [comment]
No worries! Was really grateful to find this component; saved me the trouble of wiring together my own. Happy to help/work on it if you're so inclined!

**Comment by dozoisch** [comment]
Yeah sure! 

Component goes in pair with https://github.com/dozoisch/react-async-script . I'll try to bump the deps and tag new versions tonight! If you have any idea of improvement go ahead and you can open issue/PR! I'll be happy to see them

**Comment by markthethomas** [comment]
Sounds great! Been pretty busy recently but I'll find some time to see what I can do to help out.

**Comment by dozoisch** [comment]
@markthethomas I've been so busy too... I'll try to tag by tomorrow night god! haha

**Pull request merged**
