### PR TITLE
Possible fix to issue #7

### PR DESCRIPTION
**Pull request by laserpants**
Remove reCAPTCHA iframe in `componentWillUnmount`. See https://github.com/dozoisch/react-google-recaptcha/issues/7

### CODE REVIEW

**Comment by johanneshilden** [comment]
Oh... and fixed the spelling of reCAPTCHA in the comment on line 85. :smile:

**Comment by dozoisch** [comment]
Alright sorry for the delay, I just tested it locally and I still get the same error.

**Comment by dozoisch** [comment]
removing all '.pls-container' seems to work, don't I'm not sure how good is that solution... There doesn't seem to be a way to identify a container to a specific captcha.

**Comment by johanneshilden** [comment]
Thanks for the feedback, I just realized that the iframe title attribute is locale-dependent, so that wasn't any good. Instead, could we try:

```
      if (element.src.indexOf('www.google.com/recaptcha') > -1 && element.parentNode) {
        element.parentNode.removeChild(element);
      }
```

**Comment by johanneshilden** [comment]
Well, I guess that still doesn't solve the problem of associating a container to a specific captcha, if there are multiple. Very frustrating.

**Comment by hartzis** [comment]
Closing as it is really old and may be fixed already.

**Pull request closed without merging**
