### PR TITLE
fix condition render function undefined

### PR DESCRIPTION
**Pull request by joshuaalpuerto**
- implement only changes for the library

### CODE REVIEW

**Comment by joshuaalpuerto** [comment]
Hopefully will fix issue #76  since this is a blocker and it will not be able to trigger `execute` method.

**Comment by stewartduffy** [comment]
Is anything holding this up?

**Comment by filippofilip95** [comment]
please merge :)

**Comment by zacanger** [comment]
Bump, sorry to jump in, but would it be possible to merge and release this? AFAICT this bug hasn't affected any of our users, but all of our E2E tests that hit a captcha are broken (probably because they move faster than real users).

**Comment by phthhieu** [comment]
I got more & more the exception recently, so wait for this merge

**Comment by dozoisch** [comment]
0.11.1

**Comment by koliada** [comment]
Will the version be bumped in npm?

**Comment by dozoisch** [comment]
@koliada oh! Forgot will do today.

**Comment by jessev123** [comment]
FYI we are still getting this error in production after upgrade to 0.11.1. Not able to repro on local but is happening in production on page reload.

**Comment by pgangwani** [comment]
@dozoisch : I am using "react-google-recaptcha": "0.9.9" version , which fix version has this change ? Any Backward compatibility issues ?

**Pull request merged**
