### PR TITLE
Fix #11 & #9

### LINKED ISSUE #11: React 0.14.0 warning
Since React have been released I get warning
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `reCAPTCHA`.

If I remove .getDOMNode() calls at lines 
https://github.com/bobiblazeski/react-google-recaptcha/blob/master/src/recaptcha.js
52 //     this.captcha.getDOMNode(); // removed
53 let id = this.props.grecaptcha.render(this.captcha, { // removed .getDOMNode() call
and rebuild I got

Warning: AsyncScriptLoader(...): React component classes must extend React.Component.warning @ 
main.js:1148 Uncaught Error: Invariant Violation: AsyncScriptLoader.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

If I remove them at the compiled code components works without warning.

### PR DESCRIPTION
**Pull request by spicydonuts**
Update to React 0.14.0 to fix issues #11 & #9.

### CODE REVIEW

**Comment by dozoisch** [comment]
Looks good! Ill merge it when I get home! Thanks

**Comment by spicydonuts** [comment]
:+1: : ]

**Comment by spicydonuts** [comment]
I forgot to update the readme.  Since you just made a release you might have noticed already, but it's currently referencing 0.13.0 and 0.4.0.

**Comment by dozoisch** [comment]
@spicydonuts Oh maybe I could've been clearer :-p Yeah I the default installation is for 0.14 and 0.4 is for 0.13

**Pull request merged**
