### PR TITLE
Changed updated for react 15.5

### LINKED ISSUE #38: React deprecation warnings
This package uses `React.propTypes` and `React.createClass` that are now deprecated and will be removed in React v16.

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

### PR DESCRIPTION
**Pull request by dozoisch**
- removed dependency on createClass.

closes #38

### CODE REVIEW

**Comment by peralmq** [comment]
Nice!

**Comment by dozoisch** [comment]
@peralmq hmm maybe the space is causing an issue. I published 0.9.1 with a fix to the peer dep. Let me know if that works!

**Comment by peralmq** [comment]
@dozoisch Hm, no that didn't change anything for me. Might be something on my side.

**Comment by peralmq** [comment]
Might be related to this yarn bug: https://github.com/yarnpkg/yarn/issues/2132

**Pull request merged**
